# Generated by Django 5.1.4 on 2025-03-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_date_customer_district_customer_house_no_and_more'),
        ('owner', '0008_price_and_weight_sell_minimum_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='rattings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.item')),
            ],
        ),
    ]
